Catalog history service beginning
Informasjonsforvaltning/catalog-history-service pull request #1
Opened 2022-12-16 07:07 UTC by MrFranzen

2023-01-06 12:05 UTC, NilsOveTen requested changes
Hadde og vært fint å droppe "begrep"-navnet til fordel for concept.

Og er ikke sikker på om vi skal forholde oss datastrukturen til de forskjellige datatypene, er kanskje greiest om dette apiet kun forholder seg til helt generelle json-dokument. Slik at datasett, api og begrep alle bruker samme logikk.

Strengt tatt tror jeg at strukturen til JSONPatch er det eneste dette apiet trenger å forholde seg til. Men det kan vi diskutere på et senere tidspunkt.

2023-01-09 14:43 UTC, NilsOveTen requested changes

2023-01-09 14:43 UTC, NilsOveTen commented on repository/repository.go
> +// JsonPatchRepository is a struct that holds a reference to a MongoDB collection
```suggestion
// BegreperRepository is a struct that holds a reference to a MongoDB collection
```

2023-01-09 14:43 UTC, NilsOveTen commented on service/jsonPatchService.go
> +type JsonPatchService struct {
denne er vel ikke i bruk? Kan vel like så greit bare slette hele service-pakken og opprette den når det blir behov

2023-01-09 14:43 UTC, NilsOveTen commented on test/init-mongo/init-mongo.js
> +db.createCollection('concepts');
Denne må være samme som blir brukt i koden, ref linje 38 i config/env/env.go.
Så enten endre her til `begreper`, eller oppdatere env slik at koden bruker collection=`concepts`

2023-01-10 08:11 UTC, NilsOveTen approved these changes
Klager ikke om du i tillegg bytter ut alt av "begrep" med "concept"

2023-01-10 09:10 UTC, MrFranzen commented
> Klager ikke om du i tillegg bytter ut alt av "begrep" med "concept"

Fixed

2023-01-10 09:12 UTC, NilsOveTen approved these changes
:tada:

2023-01-10 09:14 UTC, merged