API iteration #2
Informasjonsforvaltning/catalog-history-service pull request #7
Opened 2023-01-24 14:39 UTC by MrFranzen

2023-01-31 09:27 UTC, jeffreiffers commented
Build feiler

2023-01-31 09:36 UTC, NilsOveTen requested changes

2023-01-31 09:36 UTC, NilsOveTen commented on handlers/getUpdateHandler.go
> +package handlers
Sikert greit å bare legge alt av handlers ang. begrep i samme fil, kall den `conceptHandlers.go` elns

Blir enklere når vi en dag legger til flere ressurstyper

2023-01-31 09:36 UTC, NilsOveTen commented on repository/concept.go
> +func (r ConceptsRepositoryImp) GetConceptUpdates(ctx context.Context, query bson.D) ([]*model.UpdateDbo, error) {
```suggestion
func (r ConceptsRepositoryImp) GetConceptUpdates(ctx context.Context, query bson.D) ([]*model.UpdateMeta, error) {
```

2023-01-31 09:36 UTC, NilsOveTen commented on repository/concept.go
> +func (r ConceptsRepositoryImp) GetConceptUpdates(ctx context.Context, query bson.D) ([]*model.UpdateDbo, error) {
Men sikkert greit å bare ta det i en ny pr

2023-01-31 09:36 UTC, NilsOveTen commented on repository/concept.go
> +func (r ConceptsRepositoryImp) GetConceptUpdate(ctx context.Context, conceptId string) (*model.UpdateDbo, error) {
```suggestion
func (r ConceptsRepositoryImp) GetConceptUpdate(ctx context.Context, conceptId string) (*model.UpdateDiff, error) {
```
Men ja, ta denne i ny pr

2023-01-31 09:36 UTC, NilsOveTen commented on config/env/env.go
> +	Concepts: "/concepts",
```suggestion
	ConceptUpdate: "/concepts/:conceptId/:updateId",
```

2023-01-31 09:36 UTC, NilsOveTen commented on config/setupRouter.go
> +	e.GET(env.PathValues.Concepts, handlers.GetAllHandler())
```suggestion
	e.GET(env.PathValues.Concepts, handlers.GetAllHandler())
```
```suggestion
	e.GET(env.PathValues.Concept, handlers.GetConceptUpdatesHandler())
```

2023-01-31 09:36 UTC, NilsOveTen commented on config/setupRouter.go
> +	e.GET(env.PathValues.Concept, handlers.GetUpdateHandler())
```suggestion
	e.GET(env.PathValues.ConceptUpdate, handlers.GetConceptUpdateHandler())
```

2023-01-31 09:36 UTC, NilsOveTen commented on service/update.go
> +func (service *UpdateServiceImp) GetConceptUpdate(ctx context.Context, conceptId string) (*model.UpdateDbo, int) {
```suggestion
func (service *UpdateServiceImp) GetConceptUpdate(ctx context.Context, updateId string) (*model.UpdateDbo, int) {
```

2023-01-31 09:36 UTC, NilsOveTen commented on service/update.go
> +	conceptUpdate, err := service.ConceptsRepository.GetConceptUpdate(ctx, conceptId)
```suggestion
	conceptUpdate, err := service.ConceptsRepository.GetConceptUpdate(ctx, updateId)
```

2023-01-31 09:36 UTC, NilsOveTen commented on service/update.go
> +		query = append(query, bson.E{Key: "id", Value: conceptId})
```suggestion
		query = append(query, bson.E{Key: "resourceId", Value: conceptId})
```

2023-01-31 09:36 UTC, NilsOveTen commented on repository/concept.go
> +func (r ConceptsRepositoryImp) GetConceptUpdate(ctx context.Context, conceptId string) (*model.UpdateDbo, error) {
```suggestion
func (r ConceptsRepositoryImp) GetConceptUpdate(ctx context.Context, conceptId string, updateId string) (*model.UpdateDbo, error) {
```

2023-01-31 09:36 UTC, NilsOveTen commented on repository/concept.go
> +	filter := bson.D{{Key: "id", Value: conceptId}}
```suggestion
	filter := bson.D{{Key: "id", Value: updateId}, {Key: "resourceId", Value: conceptId}}
```

2023-01-31 14:08 UTC, MrFranzen commented
@jeffreiffers Nå feiler den ikke lenger

2023-01-31 14:12 UTC, NilsOveTen commented on test/init-mongo/init-mongo.js
> +    "id": "123456789",
```suggestion
    "id": "123",
    "resourceId": "123456789",
```

2023-02-01 07:18 UTC, NilsOveTen requested changes
Tror du mangler noe ang go i PATH, siden binærfila blir bygd til prosjektmappa her.

Står noe om mac her: https://go.dev/doc/install#tarball_non_standard

Oppdater PATH og slett binærfila herfra

2023-02-01 07:18 UTC, NilsOveTen commented on handlers/conceptHandlers.go
> +		logrus.Infof("Get concept update with id: %s", conceptId)
```suggestion
		logrus.Infof("Get update %s for concept %s", updateId, conceptId)
```

2023-02-01 07:18 UTC, NilsOveTen commented on handlers/conceptHandlers.go
> +		logrus.Infof("Concept update received.")
```suggestion
                conceptId := c.Param("conceptId")
		logrus.Infof("Update for concept %s received.", conceptId)
```

2023-02-01 07:18 UTC, NilsOveTen commented on handlers/conceptHandlers.go
> +			newId, err := service.StoreConceptUpdate(c.Request.Context(), bytes, c.Param("conceptId"))
```suggestion
			newId, err := service.StoreConceptUpdate(c.Request.Context(), bytes, conceptId)
```

2023-02-01 07:18 UTC, NilsOveTen commented on handlers/conceptHandlers.go
> +				c.Writer.Header().Add("Location", "/concepts/"+*newId)
```suggestion
				c.Writer.Header().Add("Location", "/concepts/" + conceptId + "/"+*newId)
```

2023-02-01 07:45 UTC, NilsOveTen approved these changes

2023-02-01 07:46 UTC, merged